package tsgen

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"

	chirpc "github.com/iambpn/chirpc/v1"
)

func newTestRouter() *chirpc.RPCRouter {
	r := chirpc.NewRPCRouter()
	chirpc.AddHandler(r, chirpc.MethodGet, "/ping", func(req *http.Request) (*chirpc.HttpResponse[string], *chirpc.ErrorResponse) {
		return &chirpc.HttpResponse[string]{Body: "pong"}, nil
	})
	return r
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("expected file to exist: %v", err)
	}
	return string(data)
}

func TestGenerateRPCSchemaWritesDefaultFile(t *testing.T) {
	t.Chdir(t.TempDir())

	if err := GenerateRPCSchema(newTestRouter()); err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	content := readFile(t, "apiSchema.ts")
	if !strings.HasPrefix(content, "// Code generated by chirpc. DO NOT EDIT.\n\n") {
		t.Fatalf("expected a generated-file header, got %q", content)
	}
	if !strings.Contains(content, `"/ping": {`) {
		t.Fatalf("expected the /ping route, got %s", content)
	}
}

func TestGenerateRPCSchemaReplacesCustomPathWithoutTempFiles(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "schema.ts")
	if err := os.WriteFile(path, []byte("old"), 0600); err != nil {
		t.Fatal(err)
	}

	if err := GenerateRPCSchema(newTestRouter(), path); err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if content := readFile(t, path); !strings.Contains(content, "type ApiSchema") {
		t.Fatalf("expected the file to be replaced, got %q", content)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0644 {
		t.Fatalf("expected file mode 0644, got %v", info.Mode().Perm())
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Fatalf("expected only the schema file to remain, got %d entries", len(entries))
	}
}

func TestGenerateRPCSchemaReturnsErrorWhenWriteFails(t *testing.T) {
	unreachable := filepath.Join(t.TempDir(), "nested", "schema.ts")

	err := GenerateRPCSchema(newTestRouter(), unreachable)
	if err == nil || !strings.Contains(err.Error(), "failed to write types to file") {
		t.Fatalf("expected a write error, got %v", err)
	}
}

func TestConvertToTsReturnsRouteErrors(t *testing.T) {
	r := chirpc.NewRPCRouter()
	chirpc.Route(r, "/child", func(c *chirpc.RPCRouter) {
		chirpc.RegisterErrorHandler(c, func(req *http.Request, err *chirpc.ErrorResponse) *chirpc.HttpResponse[string] {
			return nil
		})
	})

	if _, err := ConvertToTs(r); err == nil {
		t.Fatal("expected an error for a mismatched child error type")
	}
}
