// Package tsgen generates the TypeScript ApiSchema for a chirpc router.
//
// It is a separate package because it links the TypeScript compiler, which makes
// a binary much larger. Import it only in the program that generates the schema,
// such as a go:generate command, and not in the production server.
package tsgen

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/iambpn/chirpc/internal/typescript"
	chirpc "github.com/iambpn/chirpc/v1"
)

// header marks the file as generated, so editors and linters treat it that way.
const header = "// Code generated by chirpc. DO NOT EDIT.\n\n"

// ConvertToTs returns the generated TypeScript for all handlers registered on r and its child routers.
func ConvertToTs(r *chirpc.RPCRouter) (string, error) {
	typescriptCode, err := typescript.Convert(r.RPCSchemas())
	if err != nil {
		return "", err
	}
	return header + typescriptCode, nil
}

// GenerateRPCSchema generates TypeScript types for all registered RPC handlers and writes them to a file.
// By default, it writes to "apiSchema.ts", but a custom path can be provided.
// The file is replaced in one step, so a reader never sees a partly written file.
func GenerateRPCSchema(r *chirpc.RPCRouter, paths ...string) error {
	path := "apiSchema.ts"
	if len(paths) > 0 {
		path = paths[0]
	}

	typescriptCode, err := ConvertToTs(r)
	if err != nil {
		return err
	}

	if err := writeFileAtomically(path, []byte(typescriptCode)); err != nil {
		return fmt.Errorf("failed to write types to file: %w", err)
	}
	return nil
}

// writeFileAtomically writes data to a temporary file next to path and then renames it to path.
func writeFileAtomically(path string, data []byte) error {
	file, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*.tmp")
	if err != nil {
		return err
	}
	tempPath := file.Name()
	defer os.Remove(tempPath)

	if _, err := file.Write(data); err != nil {
		file.Close()
		return err
	}
	if err := file.Chmod(0644); err != nil {
		file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	return os.Rename(tempPath, path)
}
